name: Automatic release from PR
on:
    pull_request:
        types: [labeled]
jobs:
    merge-and-release:
        env:
            BASENAME: panard/mtgo
        name: Merge and release
        if: contains(github.event.pull_request.labels.*.name, 'merge-and-release')
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Tags
              run: |
                echo PR_TAG=pr${{ github.event.pull_request.number }} >> $GITHUB_ENV
                echo TIMESTAMP=$(date +%F) >> $GITHUB_ENV
            - name: Login to docker hub
              uses: actions-hub/docker/login@master
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull image
              uses: actions-hub/docker@master
              with:
                  args: pull $BASENAME:$PR_TAG
            - name: automerge
              uses: pascalgn/automerge-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
                  MERGE_LABELS: ""
                  MERGE_METHOD: "rebase"
            - uses: actions/checkout@v1
              with:
                  ref: master
            - name: Git tag
              run: |
                git tag $TIMESTAMP
                git push --tags https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
            - run: docker tag $BASENAME:$PR_TAG $BASENAME:$TIMESTAMP
            - name: Push image :timestamp
              uses: actions-hub/docker@master
              with:
                args: push $BASENAME:$TIMESTAMP
            - run: docker tag $BASENAME:$PR_TAG $BASENAME:latest
            - name: Push image :latest
              uses: actions-hub/docker@master
              with:
                args: push $BASENAME:latest
    default:
        name: default
        runs-on: ubuntu-latest
        steps:
            - run: echo 1
